theme: jekyll-theme-slate
title:  Web3 Security Tools Seminar (W3ST)
description: A highly technical seminar for builders of blockchain security tools during Devconnect 2025.
url: "https://montyly.github.io/w3st"
twitter_username: montyly
github_username: montyly
